/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search records
         * @description Full-text search in Greek (accents and case ignored, words stemmed), typo-tolerant, Greeklish-aware, with filters. An ΑΔΑΜ or ΑΔΑ finds that record; a nine-digit VAT number finds records of that organisation or contractor.
         */
        get: operations["SearchItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one record by its ΑΔΑΜ (ΚΗΜΔΗΣ) or ΑΔΑ (Διαύγεια) */
        get: operations["GetItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organisations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a contracting authority with its activity and recent records */
        get: operations["GetOrganisation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cpv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find CPV codes by label (Greek or English) or code prefix
         * @description For picking a trade: at most 12 codes, broad categories first. Needs at least 2 characters.
         */
        get: operations["FindCpv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** When the data was last refreshed from each source */
        get: operations["GetStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public metrics: records per source, ingestion lag and runs, and usage totals */
        get: operations["GetMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sitemap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How many pages of record identifiers the sitemap has */
        get: operations["GetSitemapIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sitemap/items/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Record identifiers for search engines, 50000 per page */
        get: operations["GetSitemapItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sitemap/organisations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identifiers of organisations that have records */
        get: operations["GetSitemapOrganisations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email a one-time sign-in link (always accepted; never reveals whether an account exists) */
        post: operations["RequestLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a sign-in link's token for a session token */
        post: operations["VerifyLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End this session */
        post: operations["Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in account and its saved searches */
        get: operations["GetAccount"];
        put?: never;
        post?: never;
        /** Delete the account and everything linked to it */
        delete: operations["DeleteAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Choose how often alerts are emailed: daily, weekly or paused */
        put: operations["SetDigest"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/saved-searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save a search for daily alerts */
        post: operations["SaveSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/saved-searches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Stop alerts for a saved search */
        delete: operations["DeleteSavedSearch"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The account's active API keys (without the keys themselves) */
        get: operations["ListApiKeys"];
        put?: never;
        /** Create an API key; the key is returned once */
        post: operations["CreateApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: operations["RevokeApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountView: {
            email: string;
            locale: string;
            savedSearches: components["schemas"]["SavedSearchView"][];
            digestFrequency: string;
        };
        ApiKeyRequest: {
            name: null | string;
        };
        ApiKeyView: {
            /** Format: uuid */
            id: string;
            name: string;
            prefix: string;
            /** Format: int32 */
            permitsPerMinute: number;
            /** Format: date-time */
            createdAt: string;
        };
        CodeLabel: {
            code: string;
            labelEl: null | string;
            labelEn: null | string;
        };
        ContractorSpend: {
            name: string;
            /** Format: int32 */
            awards: number;
            /** Format: double */
            amountEur: number;
            /** Format: double */
            paidEur: number;
        };
        CreatedApiKey: {
            apiKey: components["schemas"]["ApiKeyView"];
            key: string;
        };
        DataStatus: {
            /** Format: date-time */
            updatedAt: null | string;
            sources: components["schemas"]["SourceStatus"][];
        };
        DigestSettingsRequest: {
            frequency: string;
        };
        DominantSupplier: {
            name: string;
            /** Format: double */
            share: number;
            /** Format: int32 */
            awards: number;
            /** Format: int32 */
            totalAwards: number;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        IngestionRunSummary: {
            source: string;
            mode: string;
            status: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: double */
            durationSeconds: null | number;
            /** Format: int32 */
            fetched: number;
            /** Format: int32 */
            inserted: number;
            /** Format: int32 */
            updated: number;
        };
        ItemContractorView: {
            name: string;
            role: string;
            /** Format: double */
            amountEur: null | number;
            countryCode: null | string;
        };
        ItemDetail: {
            sourceId: string;
            source: string;
            kind: string;
            title: string;
            description: null | string;
            organisation: null | components["schemas"]["OrganisationRef"];
            /** Format: double */
            amountEur: null | number;
            /** Format: double */
            amountWithVatEur: null | number;
            /** Format: date-time */
            publishedAt: string;
            /** Format: date */
            signedOn: null | string;
            /** Format: date-time */
            deadlineAt: null | string;
            /** Format: date */
            startsOn: null | string;
            /** Format: date */
            endsOn: null | string;
            cancelled: boolean;
            /** Format: date */
            cancelledOn: null | string;
            cpv: components["schemas"]["CodeLabel"][];
            nuts: null | components["schemas"]["CodeLabel"];
            contractors: components["schemas"]["ItemContractorView"][];
            links: components["schemas"]["ItemLinkView"][];
            /** Format: uri */
            documentUrl: null | string;
            supersededBy: null | string;
            procedure?: null | string;
            /** Format: int32 */
            offersReceived?: null | number;
            signals?: null | string[];
            amountImplausible?: boolean;
        };
        ItemLinkView: {
            relation: string;
            source: string;
            sourceId: string;
            kind: null | string;
            title: null | string;
        };
        ItemSummary: {
            sourceId: string;
            source: string;
            kind: string;
            title: string;
            organisation: null | components["schemas"]["OrganisationRef"];
            /** Format: double */
            amountEur: null | number;
            /** Format: date-time */
            publishedAt: string;
            /** Format: date-time */
            deadlineAt: null | string;
            nutsCode: null | string;
            cpvCodes: string[];
            cancelled: boolean;
            /** Format: double */
            amountWithVatEur: null | number;
            signals?: null | string[];
            amountImplausible?: boolean;
        };
        LoginRequest: {
            email: string;
            locale: null | string;
        };
        OrganisationDetail: {
            id: string;
            nameEl: string;
            nameEn: null | string;
            type: null | string;
            taxId: null | string;
            parent: null | components["schemas"]["OrganisationRef"];
            /** Format: uri */
            website: null | string;
            itemCounts: {
                [key: string]: number;
            };
            /** Format: double */
            awardedLast12MonthsEur: null | number;
            /** Format: double */
            paidLast12MonthsEur: null | number;
            awardedByYear: components["schemas"]["YearSpend"][];
            topContractors: components["schemas"]["ContractorSpend"][];
            recentItems: components["schemas"]["ItemSummary"][];
            dominantSupplier?: null | components["schemas"]["DominantSupplier"];
        };
        OrganisationRef: {
            id: string;
            name: string;
        };
        PublicMetrics: {
            sources: components["schemas"]["SourceMetrics"][];
            recentRuns: components["schemas"]["IngestionRunSummary"][];
            /** Format: int32 */
            users: number;
            /** Format: int32 */
            savedSearches: number;
            /** Format: int32 */
            alertsLast7Days: number;
            /** Format: int32 */
            apiKeys: number;
        };
        SavedSearchRequest: {
            name: null | string;
            q: null | string;
            kind: null | string;
            cpv: null | string;
            nuts: null | string;
            /** Format: double */
            minAmount: null | number;
            /** Format: double */
            maxAmount: null | number;
        };
        SavedSearchView: {
            /** Format: uuid */
            id: string;
            name: string;
            q: null | string;
            kind: null | string;
            cpv: null | string;
            nuts: null | string;
            /** Format: double */
            minAmount: null | number;
            /** Format: double */
            maxAmount: null | number;
            /** Format: date-time */
            createdAt: string;
        };
        SearchItemsResult: {
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            mode: string;
            items: components["schemas"]["ItemSummary"][];
            /** @default false */
            totalCapped: boolean;
        };
        SessionResult: {
            sessionToken: string;
            /** Format: date-time */
            expiresAt: string;
        };
        SitemapEntry: {
            id: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SitemapIndex: {
            /** Format: int32 */
            itemPages: number;
        };
        SourceMetrics: {
            source: string;
            /** Format: int64 */
            records: number;
            /** Format: date-time */
            updatedAt: null | string;
            /** Format: double */
            lagMinutes: null | number;
            /** Format: int32 */
            runsSucceeded: number;
            /** Format: int32 */
            runsTotal: number;
        };
        SourceStatus: {
            source: string;
            /** Format: date-time */
            updatedAt: null | string;
        };
        VerifyRequest: {
            token: string;
        };
        YearSpend: {
            /** Format: int32 */
            year: number;
            /** Format: int32 */
            awards: number;
            /** Format: double */
            amountEur: number;
            /** Format: double */
            approvedEur: number;
            /** Format: double */
            paidEur: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    SearchItems: {
        parameters: {
            query?: {
                q?: string;
                kind?: string[];
                cpv?: string;
                nuts?: string;
                organisation?: string;
                minAmount?: number;
                maxAmount?: number;
                from?: string;
                to?: string;
                page?: number;
                pageSize?: number;
                sort?: string;
                signal?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchItemsResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FindCpv: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeLabel"][];
                };
            };
        };
    };
    GetStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStatus"];
                };
            };
        };
    };
    GetMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicMetrics"];
                };
            };
        };
    };
    GetSitemapIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitemapIndex"];
                };
            };
        };
    };
    GetSitemapItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitemapEntry"][];
                };
            };
        };
    };
    GetSitemapOrganisations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitemapEntry"][];
                };
            };
        };
    };
    RequestLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    VerifyLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountView"];
                };
            };
        };
    };
    DeleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SetDigest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DigestSettingsRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    SaveSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedSearchRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    DeleteSavedSearch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyView"][];
                };
            };
        };
    };
    CreateApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedApiKey"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    RevokeApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
