// <auto-generated />
using System;
using IxnosData.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace IxnosData.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IxnosDataDbContext))]
    [Migration("20260924064545_AddProcedureAndOffers")]
    partial class AddProcedureAndOffers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IxnosData.Domain.Alerts.AlertDelivery", b =>
                {
                    b.Property<Guid>("SavedSearchId")
                        .HasColumnType("uuid")
                        .HasColumnName("saved_search_id");

                    b.Property<string>("ItemSourceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("item_source_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("SavedSearchId", "ItemSourceId")
                        .HasName("pk_alert_delivery");

                    b.ToTable("alert_delivery", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Alerts.SavedSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CheckedUpTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_up_to");

                    b.Property<string>("Cpv")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cpv");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_amount");

                    b.Property<decimal?>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("min_amount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Nuts")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nuts");

                    b.Property<string>("Query")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("query");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_search");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_saved_search_user_id");

                    b.ToTable("saved_search", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Contractors.Contractor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TaxId")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id")
                        .HasName("pk_contractor");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_contractor_tax_id")
                        .HasFilter("tax_id IS NOT NULL");

                    b.ToTable("contractor", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Contractors.ItemContractor", b =>
                {
                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<long>("ContractorId")
                        .HasColumnType("bigint")
                        .HasColumnName("contractor_id");

                    b.Property<string>("Role")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<decimal?>("AmountEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_eur");

                    b.HasKey("ItemId", "ContractorId", "Role")
                        .HasName("pk_item_contractor");

                    b.HasIndex("ContractorId")
                        .HasDatabaseName("ix_item_contractor_contractor_id");

                    b.ToTable("item_contractor", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Items.ItemLink", b =>
                {
                    b.Property<long>("FromItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_item_id");

                    b.Property<string>("Relation")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("relation");

                    b.Property<string>("ToSource")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("to_source");

                    b.Property<string>("ToSourceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_source_id");

                    b.Property<long?>("ToItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_item_id");

                    b.HasKey("FromItemId", "Relation", "ToSource", "ToSourceId")
                        .HasName("pk_item_link");

                    b.HasIndex("ToItemId")
                        .HasDatabaseName("ix_item_link_to_item_id");

                    b.HasIndex("ToSource", "ToSourceId")
                        .HasDatabaseName("ix_item_link_to_source_to_source_id");

                    b.ToTable("item_link", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Items.ProcurementItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AmountEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_eur");

                    b.Property<decimal?>("AmountWithVatEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_with_vat_eur");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("cancelled");

                    b.Property<DateOnly?>("CancelledOn")
                        .HasColumnType("date")
                        .HasColumnName("cancelled_on");

                    b.Property<string>("ContractType")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("contract_type");

                    b.PrimitiveCollection<string[]>("CpvCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("cpv_codes");

                    b.Property<DateTimeOffset?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Keywords")
                        .HasColumnType("text")
                        .HasColumnName("keywords");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<string>("NutsCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nuts_code");

                    b.Property<int?>("OffersReceived")
                        .HasColumnType("integer")
                        .HasColumnName("offers_received");

                    b.Property<string>("OrganisationId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("organisation_id");

                    b.Property<string>("ProcedureType")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("procedure_type");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw");

                    b.Property<NpgsqlTsVector>("Search")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search")
                        .HasComputedColumnSql("setweight(to_tsvector('ixnos_data_greek'::regconfig, title), 'A')\n|| setweight(to_tsvector('ixnos_data_greek'::regconfig, coalesce(description, '')), 'B')\n|| setweight(to_tsvector('ixnos_data_greek'::regconfig, coalesce(keywords, '')), 'C')", true);

                    b.Property<string>("SearchKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_key");

                    b.Property<DateOnly?>("SignedOn")
                        .HasColumnType("date")
                        .HasColumnName("signed_on");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at");

                    b.Property<DateOnly?>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("SupersededBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("superseded_by");

                    b.Property<string>("TextNormalised")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_normalised");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_procurement_item");

                    b.HasIndex("CpvCodes")
                        .HasDatabaseName("ix_procurement_item_cpv_codes");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CpvCodes"), "gin");

                    b.HasIndex("IngestedAt")
                        .HasDatabaseName("ix_procurement_item_ingested_at");

                    b.HasIndex("NutsCode")
                        .HasDatabaseName("ix_procurement_item_nuts_code");

                    b.HasIndex("PublishedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_procurement_item_published_at");

                    b.HasIndex("Search")
                        .HasDatabaseName("ix_procurement_item_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Search"), "gin");

                    b.HasIndex("SearchKey")
                        .HasDatabaseName("ix_procurement_item_search_key");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchKey"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchKey"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TextNormalised")
                        .HasDatabaseName("ix_procurement_item_text_normalised");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TextNormalised"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("TextNormalised"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Kind", "PublishedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_procurement_item_kind_published_at");

                    b.HasIndex("OrganisationId", "PublishedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_procurement_item_organisation_id_published_at");

                    b.HasIndex("Source", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_procurement_item_source_source_id");

                    b.ToTable("procurement_item", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Operations.IngestionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("Errors")
                        .HasColumnType("integer")
                        .HasColumnName("errors");

                    b.Property<int>("Fetched")
                        .HasColumnType("integer")
                        .HasColumnName("fetched");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("Inserted")
                        .HasColumnType("integer")
                        .HasColumnName("inserted");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("Updated")
                        .HasColumnType("integer")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_run");

                    b.HasIndex("Source", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ingestion_run_source_started_at");

                    b.ToTable("ingestion_run", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Organisations.Organisation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("id");

                    b.Property<string>("NameEl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_el");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("NutsCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nuts_code");

                    b.Property<string>("ParentId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("parent_id");

                    b.Property<string>("TaxId")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("tax_id");

                    b.Property<string>("Type")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_organisation");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_organisation_parent_id");

                    b.HasIndex("TaxId")
                        .HasDatabaseName("ix_organisation_tax_id");

                    b.ToTable("organisation", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Reference.CpvCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("LabelEl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_el");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_code");

                    b.HasKey("Code")
                        .HasName("pk_cpv_code");

                    b.HasIndex("ParentCode")
                        .HasDatabaseName("ix_cpv_code_parent_code");

                    b.ToTable("cpv_code", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Reference.NutsRegion", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code");

                    b.Property<string>("LabelEl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_el");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("parent_code");

                    b.HasKey("Code")
                        .HasName("pk_nuts_region");

                    b.HasIndex("ParentCode")
                        .HasDatabaseName("ix_nuts_region_parent_code");

                    b.ToTable("nuts_region", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Users.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("PermitsPerMinute")
                        .HasColumnType("integer")
                        .HasColumnName("permits_per_minute");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("prefix");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_api_key");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_key_key_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_api_key_user_id");

                    b.ToTable("api_key", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Users.LoginToken", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("locale");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("TokenHash")
                        .HasName("pk_login_token");

                    b.HasIndex("Email", "CreatedAt")
                        .HasDatabaseName("ix_login_token_email_created_at");

                    b.ToTable("login_token", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Users.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("locale");

                    b.HasKey("Id")
                        .HasName("pk_user_account");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_account_email");

                    b.ToTable("user_account", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Users.UserSession", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TokenHash")
                        .HasName("pk_user_session");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_session_user_id");

                    b.ToTable("user_session", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Alerts.AlertDelivery", b =>
                {
                    b.HasOne("IxnosData.Domain.Alerts.SavedSearch", null)
                        .WithMany()
                        .HasForeignKey("SavedSearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alert_delivery_saved_searches_saved_search_id");
                });

            modelBuilder.Entity("IxnosData.Domain.Alerts.SavedSearch", b =>
                {
                    b.HasOne("IxnosData.Domain.Users.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_search_user_accounts_user_id");
                });

            modelBuilder.Entity("IxnosData.Domain.Contractors.ItemContractor", b =>
                {
                    b.HasOne("IxnosData.Domain.Contractors.Contractor", null)
                        .WithMany()
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_item_contractor_contractor_contractor_id");

                    b.HasOne("IxnosData.Domain.Items.ProcurementItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_contractor_procurement_items_item_id");
                });

            modelBuilder.Entity("IxnosData.Domain.Items.ItemLink", b =>
                {
                    b.HasOne("IxnosData.Domain.Items.ProcurementItem", null)
                        .WithMany()
                        .HasForeignKey("FromItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_link_procurement_items_from_item_id");

                    b.HasOne("IxnosData.Domain.Items.ProcurementItem", null)
                        .WithMany()
                        .HasForeignKey("ToItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_item_link_procurement_items_to_item_id");
                });

            modelBuilder.Entity("IxnosData.Domain.Items.ProcurementItem", b =>
                {
                    b.HasOne("IxnosData.Domain.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_procurement_item_organisation_organisation_id");
                });

            modelBuilder.Entity("IxnosData.Domain.Organisations.Organisation", b =>
                {
                    b.HasOne("IxnosData.Domain.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_organisation_organisation_parent_id");
                });

            modelBuilder.Entity("IxnosData.Domain.Reference.CpvCode", b =>
                {
                    b.HasOne("IxnosData.Domain.Reference.CpvCode", null)
                        .WithMany()
                        .HasForeignKey("ParentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cpv_code_cpv_code_parent_code");
                });

            modelBuilder.Entity("IxnosData.Domain.Reference.NutsRegion", b =>
                {
                    b.HasOne("IxnosData.Domain.Reference.NutsRegion", null)
                        .WithMany()
                        .HasForeignKey("ParentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_nuts_region_nuts_region_parent_code");
                });

            modelBuilder.Entity("IxnosData.Domain.Users.ApiKey", b =>
                {
                    b.HasOne("IxnosData.Domain.Users.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_user_accounts_user_id");
                });

            modelBuilder.Entity("IxnosData.Domain.Users.UserSession", b =>
                {
                    b.HasOne("IxnosData.Domain.Users.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_session_user_account_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
