// <auto-generated />
using System;
using IxnosData.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IxnosData.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IxnosDataDbContext))]
    [Migration("20260922204822_AddOrganisation")]
    partial class AddOrganisation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IxnosData.Domain.Operations.IngestionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("Errors")
                        .HasColumnType("integer")
                        .HasColumnName("errors");

                    b.Property<int>("Fetched")
                        .HasColumnType("integer")
                        .HasColumnName("fetched");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("Inserted")
                        .HasColumnType("integer")
                        .HasColumnName("inserted");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("Updated")
                        .HasColumnType("integer")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_run");

                    b.HasIndex("Source", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ingestion_run_source_started_at");

                    b.ToTable("ingestion_run", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Organisations.Organisation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("id");

                    b.Property<string>("NameEl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_el");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("NutsCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nuts_code");

                    b.Property<string>("ParentId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("parent_id");

                    b.Property<string>("TaxId")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("tax_id");

                    b.Property<string>("Type")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_organisation");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_organisation_parent_id");

                    b.HasIndex("TaxId")
                        .HasDatabaseName("ix_organisation_tax_id");

                    b.ToTable("organisation", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Reference.CpvCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("LabelEl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_el");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_code");

                    b.HasKey("Code")
                        .HasName("pk_cpv_code");

                    b.HasIndex("ParentCode")
                        .HasDatabaseName("ix_cpv_code_parent_code");

                    b.ToTable("cpv_code", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Reference.NutsRegion", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code");

                    b.Property<string>("LabelEl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_el");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("parent_code");

                    b.HasKey("Code")
                        .HasName("pk_nuts_region");

                    b.HasIndex("ParentCode")
                        .HasDatabaseName("ix_nuts_region_parent_code");

                    b.ToTable("nuts_region", (string)null);
                });

            modelBuilder.Entity("IxnosData.Domain.Organisations.Organisation", b =>
                {
                    b.HasOne("IxnosData.Domain.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_organisation_organisation_parent_id");
                });

            modelBuilder.Entity("IxnosData.Domain.Reference.CpvCode", b =>
                {
                    b.HasOne("IxnosData.Domain.Reference.CpvCode", null)
                        .WithMany()
                        .HasForeignKey("ParentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cpv_code_cpv_code_parent_code");
                });

            modelBuilder.Entity("IxnosData.Domain.Reference.NutsRegion", b =>
                {
                    b.HasOne("IxnosData.Domain.Reference.NutsRegion", null)
                        .WithMany()
                        .HasForeignKey("ParentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_nuts_region_nuts_region_parent_code");
                });
#pragma warning restore 612, 618
        }
    }
}
