// The 45 CPV divisions (the first two digits of a code), for the trade filter. Codes and labels
// from pipeline/src/ixnos_data_pipeline/reference/data/cpv_2008.csv. The API matches by prefix, so a
// division covers every code under it.

export const CPV_DIVISIONS: ReadonlyArray<{ code: string; nameEl: string; nameEn: string }> = [
  { code: "03", nameEl: "Προϊόντα γεωργίας, κτηνοτροφίας, αλιείας, δασοκομίας και συναφή προϊόντα", nameEn: "Agricultural, farming, fishing, forestry and related products" },
  { code: "09", nameEl: "Πετρελαϊκά προϊόντα, καύσιμα, ηλεκτρική και άλλες πηγές ενέργειας", nameEn: "Petroleum products, fuel, electricity and other sources of energy" },
  { code: "14", nameEl: "Εξορυκτικά προϊόντα, βασικά μέταλλα και συναφή προϊόντα", nameEn: "Mining, basic metals and related products" },
  { code: "15", nameEl: "Τρόφιμα, ποτά, καπνός και συναφή προϊόντα", nameEn: "Food, beverages, tobacco and related products" },
  { code: "16", nameEl: "Γεωργικά μηχανήματα", nameEn: "Agricultural machinery" },
  { code: "18", nameEl: "Είδη και εξαρτήματα ρουχισμού, υπόδησης, αποσκευών", nameEn: "Clothing, footwear, luggage articles and accessories" },
  { code: "19", nameEl: "Δέρμα και υφάσματα, υλικά από πλαστικό και καουτσούκ", nameEn: "Leather and textile fabrics, plastic and rubber materials" },
  { code: "22", nameEl: "Έντυπο υλικό και συναφή προϊόντα", nameEn: "Printed matter and related products" },
  { code: "24", nameEl: "Χημικά προϊόντα", nameEn: "Chemical products" },
  { code: "30", nameEl: "Μηχανήματα γραφείου και υπολογιστές, εξοπλισμός και προμήθειες εκτός από έπιπλα και πακέτα λογισμικών", nameEn: "Office and computing machinery, equipment and supplies except furniture and software packages" },
  { code: "31", nameEl: "Ηλεκτρικές μηχανές, συσκευές, εξοπλισμός και αναλώσιμα· φωτισμός", nameEn: "Electrical machinery, apparatus, equipment and consumables; lighting" },
  { code: "32", nameEl: "Εξοπλισμός ραδιοφωνίας, τηλεόρασης, επικοινωνιών, τηλεπικοινωνιών και συναφής εξοπλισμός", nameEn: "Radio, television, communication, telecommunication and related equipment" },
  { code: "33", nameEl: "Ιατρικές συσκευές, φαρμακευτικά προϊόντα και προϊόντα ατομικής περιποίησης", nameEn: "Medical equipments, pharmaceuticals and personal care products" },
  { code: "34", nameEl: "Εξοπλισμός μεταφοράς και βοηθητικά μέσα μεταφοράς", nameEn: "Transport equipment and auxiliary products to transportation" },
  { code: "35", nameEl: "Εξοπλισμός ασφαλείας και πυρόσβεσης, αστυνομικός και αμυντικός εξοπλισμός", nameEn: "Security, fire-fighting, police and defence equipment" },
  { code: "37", nameEl: "Μουσικά όργανα, είδη αθλητισμού, επιτραπέζια παιχνίδια, παιδικά παιχνίδια, είδη χειροτεχνίας, υλικά και εξαρτήματα καλλιτεχνίας", nameEn: "Musical instruments, sport goods, games, toys, handicraft, art materials and accessories" },
  { code: "38", nameEl: "Εξοπλισμός εργαστηριακός, οπτικός και ακριβείας (εκτός από γυαλιά)", nameEn: "Laboratory, optical and precision equipments (excl. glasses)" },
  { code: "39", nameEl: "Έπιπλα (όπου περιλαμβάνονται έπιπλα γραφείου), επιπλώσεις, οικιακές συσκευές (εκτός από συσκευές φωτισμού) και προϊόντα καθαρισμού", nameEn: "Furniture (incl. office furniture), furnishings, domestic appliances (excl. lighting) and cleaning products" },
  { code: "41", nameEl: "Συλλογή και καθαρισμός νερού", nameEn: "Collected and purified water" },
  { code: "42", nameEl: "Μηχανήματα βιομηχανικών εγκαταστάσεων", nameEn: "Industrial machinery" },
  { code: "43", nameEl: "Μηχανήματα για εξοπλισμό ορυχείων, λατομείων, κατασκευών", nameEn: "Machinery for mining, quarrying, construction equipment" },
  { code: "44", nameEl: "Δομές και υλικά κατασκευαστικών έργων· βοηθήματα κατασκευαστικών έργων (εκτός από ηλεκτρικές συσκευές)", nameEn: "Construction structures and materials; auxiliary products to construction (except electric apparatus)" },
  { code: "45", nameEl: "Κατασκευαστικές εργασίες", nameEn: "Construction work" },
  { code: "48", nameEl: "Πακέτα λογισμικού και συστήματα πληροφορικής", nameEn: "Software package and information systems" },
  { code: "50", nameEl: "Υπηρεσίες επισκευής και συντήρησης", nameEn: "Repair and maintenance services" },
  { code: "51", nameEl: "Υπηρεσίες εγκατάστασης (εκτός από υπηρεσίες εγκατάστασης λογισμικού)", nameEn: "Installation services (except software)" },
  { code: "55", nameEl: "Υπηρεσίες ξενοδοχείων, εστιατορίων και λιανικού εμπορίου", nameEn: "Hotel, restaurant and retail trade services" },
  { code: "60", nameEl: "Υπηρεσίες μεταφορών (εκτός από μεταφορά αποβλήτων)", nameEn: "Transport services (excl. Waste transport)" },
  { code: "63", nameEl: "Βοηθητικές και επικουρικές υπηρεσίες μεταφορών· υπηρεσίες ταξιδιωτικών πρακτορείων", nameEn: "Supporting and auxiliary transport services; travel agencies services" },
  { code: "64", nameEl: "Υπηρεσίες ταχυδρομείων και τηλεπικοινωνιών", nameEn: "Postal and telecommunications services" },
  { code: "65", nameEl: "Επιχειρήσεις δημόσιας ωφέλειας", nameEn: "Public utilities" },
  { code: "66", nameEl: "Χρηματοπιστωτικές και ασφαλιστικές υπηρεσίες", nameEn: "Financial and insurance services" },
  { code: "70", nameEl: "Υπηρεσίες που αφορούν τα ακίνητα", nameEn: "Real estate services" },
  { code: "71", nameEl: "Υπηρεσίες αρχιτεκτονικής, κατασκευαστικών έργων, έργων πολιτικού μηχανικού και επίβλεψης", nameEn: "Architectural, construction, engineering and inspection services" },
  { code: "72", nameEl: "Υπηρεσίες τεχνολογίας των πληροφοριών: παροχή συμβουλών, ανάπτυξη λογισμικού, Διαδίκτυο και υποστήριξη", nameEn: "IT services: consulting, software development, Internet and support" },
  { code: "73", nameEl: "Υπηρεσίες έρευνας και ανάπτυξης, καθώς και συναφείς υπηρεσίες παροχής συμβουλών", nameEn: "Research and development services and related consultancy services" },
  { code: "75", nameEl: "Υπηρεσίες δημόσιας διοίκησης, άμυνας και κοινωνικής ασφάλισης", nameEn: "Administration, defence and social security services" },
  { code: "76", nameEl: "Υπηρεσίες σχετιζόμενες με τη βιομηχανία πετρελαίου και φυσικού αερίου", nameEn: "Services related to the oil and gas industry" },
  { code: "77", nameEl: "Υπηρεσίες γεωργίας, δασοκομίας, φυτοκομίας, υδατοκαλλιέργειας και μελισσοκομίας", nameEn: "Agricultural, forestry, horticultural, aquacultural and apicultural services" },
  { code: "79", nameEl: "Επιχειρηματικές υπηρεσίες: νομικές, μάρκετινγκ, παροχής συμβουλών, πρόσληψης, εκτύπωσης και ασφάλειας", nameEn: "Business services: law, marketing, consulting, recruitment, printing and security" },
  { code: "80", nameEl: "Υπηρεσίες εκπαίδευσης και επιμόρφωσης", nameEn: "Education and training services" },
  { code: "85", nameEl: "Υγειονομικές και κοινωνικές υπηρεσίες", nameEn: "Health and social work services" },
  { code: "90", nameEl: "Υπηρεσίες λυμάτων, απορριμμάτων, καθαρισμού και περιβαλλοντικές υπηρεσίες", nameEn: "Sewage, refuse, cleaning and environmental services" },
  { code: "92", nameEl: "Ψυχαγωγικές, πολιτιστικές και αθλητικές υπηρεσίες", nameEn: "Recreational, cultural and sporting services" },
  { code: "98", nameEl: "Λοιπές κοινοτικές, κοινωνικές και ατομικές υπηρεσίες", nameEn: "Other community, social and personal services" },
];
