using IxnosData.Domain.Contractors;
using IxnosData.Domain.Items;
using IxnosData.Domain.Organisations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NpgsqlTypes;

namespace IxnosData.Infrastructure.Persistence.Configurations;

public class ProcurementItemConfiguration : IEntityTypeConfiguration<ProcurementItem>
{
    public void Configure(EntityTypeBuilder<ProcurementItem> builder)
    {
        builder.ToTable("procurement_item");
        builder.Property(item => item.Source).HasMaxLength(16);
        builder.Property(item => item.SourceId).HasMaxLength(32);
        builder.Property(item => item.Kind).HasMaxLength(24).HasConversion(new SnakeCaseEnumConverter<ItemKind>());
        builder.Property(item => item.AmountEur).HasPrecision(18, 2);
        builder.Property(item => item.AmountWithVatEur).HasPrecision(18, 2);
        builder.Property(item => item.NutsCode).HasMaxLength(5);
        builder.Property(item => item.SupersededBy).HasMaxLength(32);
        builder.Property(item => item.ProcedureType).HasMaxLength(8);
        builder.Property(item => item.ContractType).HasMaxLength(8);
        builder.Property(item => item.OrganisationId).HasMaxLength(16);
        builder.Property(item => item.Raw).HasColumnType("jsonb");
        builder.Property(item => item.IngestedAt).HasDefaultValueSql("now()");

        builder.HasOne<Organisation>().WithMany().HasForeignKey(item => item.OrganisationId)
            .OnDelete(DeleteBehavior.Restrict);

        // Full-text search: generated by PostgreSQL, so it can never disagree with the text.
        // Weighted for ranking: title A, line-item descriptions B, CPV labels C.
        // A shadow property keeps Npgsql types out of the Domain layer.
        builder.Property<NpgsqlTsVector>("Search")
            .HasComputedColumnSql(
                """
                setweight(to_tsvector('ixnos_data_greek'::regconfig, title), 'A')
                || setweight(to_tsvector('ixnos_data_greek'::regconfig, coalesce(description, '')), 'B')
                || setweight(to_tsvector('ixnos_data_greek'::regconfig, coalesce(keywords, '')), 'C')
                """,
                stored: true);
        builder.HasIndex("Search").HasMethod("gin");

        builder.HasIndex(item => new { item.Source, item.SourceId }).IsUnique();
        builder.HasIndex(item => item.TextNormalised).HasMethod("gin").HasOperators("gin_trgm_ops");
        builder.HasIndex(item => item.SearchKey).HasMethod("gin").HasOperators("gin_trgm_ops");
        builder.HasIndex(item => item.CpvCodes).HasMethod("gin");
        builder.HasIndex(item => item.PublishedAt).IsDescending();
        builder.HasIndex(item => new { item.OrganisationId, item.PublishedAt }).IsDescending(false, true);
        builder.HasIndex(item => new { item.Kind, item.PublishedAt }).IsDescending(false, true);
        builder.HasIndex(item => item.NutsCode);
        // The notifier polls for records ingested after its checkpoint.
        builder.HasIndex(item => item.IngestedAt);
    }
}

public class ItemLinkConfiguration : IEntityTypeConfiguration<ItemLink>
{
    public void Configure(EntityTypeBuilder<ItemLink> builder)
    {
        builder.ToTable("item_link");
        builder.HasKey(link => new { link.FromItemId, link.Relation, link.ToSource, link.ToSourceId });
        builder.Property(link => link.Relation).HasMaxLength(32);
        builder.Property(link => link.ToSource).HasMaxLength(16);
        builder.Property(link => link.ToSourceId).HasMaxLength(32);

        builder.HasOne<ProcurementItem>().WithMany().HasForeignKey(link => link.FromItemId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.HasOne<ProcurementItem>().WithMany().HasForeignKey(link => link.ToItemId)
            .OnDelete(DeleteBehavior.SetNull);

        // Resolving stored references once their target is ingested.
        builder.HasIndex(link => new { link.ToSource, link.ToSourceId });
    }
}

public class ContractorConfiguration : IEntityTypeConfiguration<Contractor>
{
    public void Configure(EntityTypeBuilder<Contractor> builder)
    {
        builder.ToTable("contractor");
        builder.Property(contractor => contractor.TaxId).HasMaxLength(9);
        builder.Property(contractor => contractor.CountryCode).HasMaxLength(2);
        builder.HasIndex(contractor => contractor.TaxId).IsUnique().HasFilter("tax_id IS NOT NULL");
    }
}

public class ItemContractorConfiguration : IEntityTypeConfiguration<ItemContractor>
{
    public void Configure(EntityTypeBuilder<ItemContractor> builder)
    {
        builder.ToTable("item_contractor");
        builder.HasKey(link => new { link.ItemId, link.ContractorId, link.Role });
        builder.Property(link => link.Role).HasMaxLength(16).HasConversion(new SnakeCaseEnumConverter<ContractorRole>());
        builder.Property(link => link.AmountEur).HasPrecision(18, 2);

        builder.HasOne<ProcurementItem>().WithMany().HasForeignKey(link => link.ItemId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.HasOne<Contractor>().WithMany().HasForeignKey(link => link.ContractorId)
            .OnDelete(DeleteBehavior.Restrict);

        // "Everything this contractor won or was paid", for contractor views.
        builder.HasIndex(link => link.ContractorId);
    }
}
