CREATE TABLE IF NOT EXISTS __ef_migrations_history (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE FUNCTION ixnos_unaccent(text) RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
RETURN public.unaccent('public.unaccent'::regdictionary, $1);

CREATE TEXT SEARCH CONFIGURATION ixnos_greek (COPY = pg_catalog.greek);
ALTER TEXT SEARCH CONFIGURATION ixnos_greek
    ALTER MAPPING FOR word, hword, hword_part WITH public.unaccent, greek_stem;
ALTER TEXT SEARCH CONFIGURATION ixnos_greek
    ALTER MAPPING FOR asciiword, asciihword, hword_asciipart WITH simple;

INSERT INTO __ef_migrations_history (migration_id, product_version)
VALUES ('20260922194446_ExtensionsAndGreekSearchConfig', '10.0.12');

COMMIT;

START TRANSACTION;
CREATE TABLE ingestion_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    source character varying(32) NOT NULL,
    mode character varying(32) NOT NULL,
    status character varying(16) NOT NULL,
    started_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    fetched integer NOT NULL,
    inserted integer NOT NULL,
    updated integer NOT NULL,
    errors integer NOT NULL,
    error_message text,
    details jsonb,
    CONSTRAINT pk_ingestion_run PRIMARY KEY (id)
);

CREATE INDEX ix_ingestion_run_source_started_at ON ingestion_run (source, started_at DESC);

INSERT INTO __ef_migrations_history (migration_id, product_version)
VALUES ('20260922202242_AddIngestionRun', '10.0.12');

COMMIT;

START TRANSACTION;
CREATE TABLE cpv_code (
    code character varying(10) NOT NULL,
    parent_code character varying(10),
    level smallint NOT NULL,
    label_el text NOT NULL,
    label_en text NOT NULL,
    CONSTRAINT pk_cpv_code PRIMARY KEY (code),
    CONSTRAINT fk_cpv_code_cpv_code_parent_code FOREIGN KEY (parent_code) REFERENCES cpv_code (code) ON DELETE RESTRICT
);

CREATE TABLE nuts_region (
    code character varying(5) NOT NULL,
    parent_code character varying(5),
    level smallint NOT NULL,
    label_el text NOT NULL,
    label_en text NOT NULL,
    CONSTRAINT pk_nuts_region PRIMARY KEY (code),
    CONSTRAINT fk_nuts_region_nuts_region_parent_code FOREIGN KEY (parent_code) REFERENCES nuts_region (code) ON DELETE RESTRICT
);

CREATE INDEX ix_cpv_code_parent_code ON cpv_code (parent_code);

CREATE INDEX ix_nuts_region_parent_code ON nuts_region (parent_code);

INSERT INTO __ef_migrations_history (migration_id, product_version)
VALUES ('20260922203710_AddReferenceTables', '10.0.12');

COMMIT;

START TRANSACTION;
CREATE TABLE organisation (
    id character varying(16) NOT NULL,
    name_el text NOT NULL,
    name_en text,
    type character varying(32),
    tax_id character varying(9),
    parent_id character varying(16),
    nuts_code character varying(5),
    website text,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_organisation PRIMARY KEY (id),
    CONSTRAINT fk_organisation_organisation_parent_id FOREIGN KEY (parent_id) REFERENCES organisation (id) ON DELETE RESTRICT
);

CREATE INDEX ix_organisation_parent_id ON organisation (parent_id);

CREATE INDEX ix_organisation_tax_id ON organisation (tax_id);

INSERT INTO __ef_migrations_history (migration_id, product_version)
VALUES ('20260922204822_AddOrganisation', '10.0.12');

COMMIT;

START TRANSACTION;
CREATE TABLE contractor (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tax_id character varying(9),
    name text NOT NULL,
    country_code character varying(2),
    CONSTRAINT pk_contractor PRIMARY KEY (id)
);

CREATE TABLE procurement_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    source character varying(16) NOT NULL,
    source_id character varying(32) NOT NULL,
    kind character varying(24) NOT NULL,
    title text NOT NULL,
    description text,
    keywords text,
    text_normalised text NOT NULL,
    search_key text NOT NULL,
    amount_eur numeric(18,2),
    amount_with_vat_eur numeric(18,2),
    cpv_codes text[] NOT NULL,
    nuts_code character varying(5),
    organisation_id character varying(16),
    published_at timestamp with time zone NOT NULL,
    signed_on date,
    deadline_at timestamp with time zone,
    starts_on date,
    ends_on date,
    cancelled boolean NOT NULL,
    cancelled_on date,
    source_updated_at timestamp with time zone,
    raw jsonb NOT NULL,
    ingested_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL,
    search tsvector GENERATED ALWAYS AS (setweight(to_tsvector('ixnos_greek'::regconfig, title), 'A')
|| setweight(to_tsvector('ixnos_greek'::regconfig, coalesce(description, '')), 'B')
|| setweight(to_tsvector('ixnos_greek'::regconfig, coalesce(keywords, '')), 'C')) STORED,
    CONSTRAINT pk_procurement_item PRIMARY KEY (id),
    CONSTRAINT fk_procurement_item_organisation_organisation_id FOREIGN KEY (organisation_id) REFERENCES organisation (id) ON DELETE RESTRICT
);

CREATE TABLE item_contractor (
    item_id bigint NOT NULL,
    contractor_id bigint NOT NULL,
    role character varying(16) NOT NULL,
    amount_eur numeric(18,2),
    CONSTRAINT pk_item_contractor PRIMARY KEY (item_id, contractor_id, role),
    CONSTRAINT fk_item_contractor_contractor_contractor_id FOREIGN KEY (contractor_id) REFERENCES contractor (id) ON DELETE RESTRICT,
    CONSTRAINT fk_item_contractor_procurement_items_item_id FOREIGN KEY (item_id) REFERENCES procurement_item (id) ON DELETE CASCADE
);

CREATE TABLE item_link (
    from_item_id bigint NOT NULL,
    relation character varying(32) NOT NULL,
    to_source character varying(16) NOT NULL,
    to_source_id character varying(32) NOT NULL,
    to_item_id bigint,
    CONSTRAINT pk_item_link PRIMARY KEY (from_item_id, relation, to_source, to_source_id),
    CONSTRAINT fk_item_link_procurement_items_from_item_id FOREIGN KEY (from_item_id) REFERENCES procurement_item (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_link_procurement_items_to_item_id FOREIGN KEY (to_item_id) REFERENCES procurement_item (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX ix_contractor_tax_id ON contractor (tax_id) WHERE tax_id IS NOT NULL;

CREATE INDEX ix_item_contractor_contractor_id ON item_contractor (contractor_id);

CREATE INDEX ix_item_link_to_item_id ON item_link (to_item_id);

CREATE INDEX ix_item_link_to_source_to_source_id ON item_link (to_source, to_source_id);

CREATE INDEX ix_procurement_item_cpv_codes ON procurement_item USING gin (cpv_codes);

CREATE INDEX ix_procurement_item_ingested_at ON procurement_item (ingested_at);

CREATE INDEX ix_procurement_item_kind_published_at ON procurement_item (kind, published_at DESC);

CREATE INDEX ix_procurement_item_nuts_code ON procurement_item (nuts_code);

CREATE INDEX ix_procurement_item_organisation_id_published_at ON procurement_item (organisation_id, published_at DESC);

CREATE INDEX ix_procurement_item_published_at ON procurement_item (published_at DESC);

CREATE INDEX ix_procurement_item_search ON procurement_item USING gin (search);

CREATE INDEX ix_procurement_item_search_key ON procurement_item USING gin (search_key gin_trgm_ops);

CREATE UNIQUE INDEX ix_procurement_item_source_source_id ON procurement_item (source, source_id);

CREATE INDEX ix_procurement_item_text_normalised ON procurement_item USING gin (text_normalised gin_trgm_ops);

INSERT INTO __ef_migrations_history (migration_id, product_version)
VALUES ('20260922210242_AddItemsContractorsLinks', '10.0.12');

COMMIT;

START TRANSACTION;
CREATE TABLE login_token (
    token_hash character varying(64) NOT NULL,
    email character varying(254) NOT NULL,
    locale character varying(2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    CONSTRAINT pk_login_token PRIMARY KEY (token_hash)
);

CREATE TABLE user_account (
    id uuid NOT NULL,
    email character varying(254) NOT NULL,
    locale character varying(2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_user_account PRIMARY KEY (id)
);

CREATE TABLE saved_search (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    name character varying(200) NOT NULL,
    query character varying(200),
    kind character varying(24),
    cpv character varying(10),
    nuts character varying(5),
    min_amount numeric(18,2),
    max_amount numeric(18,2),
    created_at timestamp with time zone NOT NULL,
    checked_up_to timestamp with time zone NOT NULL,
    CONSTRAINT pk_saved_search PRIMARY KEY (id),
    CONSTRAINT fk_saved_search_user_accounts_user_id FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE CASCADE
);

CREATE TABLE user_session (
    token_hash character varying(64) NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_user_session PRIMARY KEY (token_hash),
    CONSTRAINT fk_user_session_user_account_user_id FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE CASCADE
);

CREATE TABLE alert_delivery (
    saved_search_id uuid NOT NULL,
    item_source_id character varying(32) NOT NULL,
    sent_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_alert_delivery PRIMARY KEY (saved_search_id, item_source_id),
    CONSTRAINT fk_alert_delivery_saved_searches_saved_search_id FOREIGN KEY (saved_search_id) REFERENCES saved_search (id) ON DELETE CASCADE
);

CREATE INDEX ix_login_token_email_created_at ON login_token (email, created_at);

CREATE INDEX ix_saved_search_user_id ON saved_search (user_id);

CREATE UNIQUE INDEX ix_user_account_email ON user_account (email);

CREATE INDEX ix_user_session_user_id ON user_session (user_id);

INSERT INTO __ef_migrations_history (migration_id, product_version)
VALUES ('20260923073458_AddAccountsAndAlerts', '10.0.12');

COMMIT;

START TRANSACTION;
ALTER TABLE procurement_item ADD superseded_by character varying(32);

CREATE TABLE api_key (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    name character varying(100) NOT NULL,
    prefix character varying(12) NOT NULL,
    key_hash character varying(64) NOT NULL,
    permits_per_minute integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    CONSTRAINT pk_api_key PRIMARY KEY (id),
    CONSTRAINT fk_api_key_user_accounts_user_id FOREIGN KEY (user_id) REFERENCES user_account (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_api_key_key_hash ON api_key (key_hash);

CREATE INDEX ix_api_key_user_id ON api_key (user_id);

CREATE INDEX ix_procurement_item_diavgeia_version ON procurement_item ((raw->>'versionId')) WHERE source = 'diavgeia';

INSERT INTO __ef_migrations_history (migration_id, product_version)
VALUES ('20260923120430_AddSupersededAndApiKeys', '10.0.12');

COMMIT;

START TRANSACTION;
ALTER TEXT SEARCH CONFIGURATION ixnos_greek RENAME TO ixnos_data_greek;

ALTER FUNCTION ixnos_unaccent(text) RENAME TO ixnos_data_unaccent;

INSERT INTO __ef_migrations_history (migration_id, product_version)
VALUES ('20260923204614_RenameGreekSearchConfig', '10.0.12');

COMMIT;

START TRANSACTION;
ALTER TABLE procurement_item ADD contract_type character varying(8);

ALTER TABLE procurement_item ADD offers_received integer;

ALTER TABLE procurement_item ADD procedure_type character varying(8);

UPDATE procurement_item SET
    procedure_type = nullif(raw->'procedureType'->>'key', ''),
    contract_type = nullif(raw->'contractType'->>'key', ''),
    offers_received = CASE WHEN raw->>'bidsSubmitted' ~ '^[0-9]{1,6}$' THEN (raw->>'bidsSubmitted')::int END
WHERE source = 'khmdhs';

INSERT INTO __ef_migrations_history (migration_id, product_version)
VALUES ('20260924064545_AddProcedureAndOffers', '10.0.12');

COMMIT;

START TRANSACTION;
ALTER TABLE user_account ADD digest_frequency character varying(8) NOT NULL DEFAULT 'daily';

INSERT INTO __ef_migrations_history (migration_id, product_version)
VALUES ('20260924071116_AddDigestFrequency', '10.0.12');

COMMIT;

