"""The tables the pipeline writes. The schema belongs to the EF Core migrations; a test
compares these against contracts/db/schema.sql.
"""

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    Computed,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    MetaData,
    Numeric,
    SmallInteger,
    String,
    Table,
    Text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, TSVECTOR

metadata = MetaData()

ingestion_run = Table(
    "ingestion_run",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("source", String(32), nullable=False),
    Column("mode", String(32), nullable=False),
    Column("status", String(16), nullable=False),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("finished_at", DateTime(timezone=True)),
    Column("fetched", Integer, nullable=False),
    Column("inserted", Integer, nullable=False),
    Column("updated", Integer, nullable=False),
    Column("errors", Integer, nullable=False),
    Column("error_message", Text),
    Column("details", JSONB),
)

cpv_code = Table(
    "cpv_code",
    metadata,
    Column("code", String(10), primary_key=True),
    Column("parent_code", String(10), ForeignKey("cpv_code.code")),
    Column("level", SmallInteger, nullable=False),
    Column("label_el", Text, nullable=False),
    Column("label_en", Text, nullable=False),
)

nuts_region = Table(
    "nuts_region",
    metadata,
    Column("code", String(5), primary_key=True),
    Column("parent_code", String(5), ForeignKey("nuts_region.code")),
    Column("level", SmallInteger, nullable=False),
    Column("label_el", Text, nullable=False),
    Column("label_en", Text, nullable=False),
)

organisation = Table(
    "organisation",
    metadata,
    Column("id", String(16), primary_key=True),
    Column("name_el", Text, nullable=False),
    Column("name_en", Text),
    Column("type", String(32)),
    Column("tax_id", String(9)),
    Column("parent_id", String(16), ForeignKey("organisation.id")),
    Column("nuts_code", String(5)),
    Column("website", Text),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

procurement_item = Table(
    "procurement_item",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("source", String(16), nullable=False),
    Column("source_id", String(32), nullable=False),
    Column("kind", String(24), nullable=False),
    Column("title", Text, nullable=False),
    Column("description", Text),
    Column("keywords", Text),
    Column("text_normalised", Text, nullable=False),
    Column("search_key", Text, nullable=False),
    Column("amount_eur", Numeric(18, 2)),
    Column("amount_with_vat_eur", Numeric(18, 2)),
    Column("cpv_codes", ARRAY(Text), nullable=False),
    Column("nuts_code", String(5)),
    Column("organisation_id", String(16), ForeignKey("organisation.id")),
    Column("published_at", DateTime(timezone=True), nullable=False),
    Column("signed_on", Date),
    Column("deadline_at", DateTime(timezone=True)),
    Column("starts_on", Date),
    Column("ends_on", Date),
    Column("cancelled", Boolean, nullable=False),
    Column("cancelled_on", Date),
    Column("superseded_by", String(32)),
    Column("procedure_type", String(8)),
    Column("contract_type", String(8)),
    Column("offers_received", Integer),
    Column("source_updated_at", DateTime(timezone=True)),
    Column("raw", JSONB, nullable=False),
    Column("ingested_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    # Generated by PostgreSQL (weighted title A, description B, keywords C); never written here.
    Column(
        "search",
        TSVECTOR,
        Computed(
            "setweight(to_tsvector('ixnos_data_greek'::regconfig, title), 'A') || "
            "setweight(to_tsvector('ixnos_data_greek'::regconfig, coalesce(description, '')), 'B')"
            " || "
            "setweight(to_tsvector('ixnos_data_greek'::regconfig, coalesce(keywords, '')), 'C')"
        ),
    ),
)

item_link = Table(
    "item_link",
    metadata,
    Column("from_item_id", BigInteger, ForeignKey("procurement_item.id"), primary_key=True),
    Column("relation", String(32), primary_key=True),
    Column("to_source", String(16), primary_key=True),
    Column("to_source_id", String(32), primary_key=True),
    Column("to_item_id", BigInteger, ForeignKey("procurement_item.id")),
)

contractor = Table(
    "contractor",
    metadata,
    Column("id", BigInteger, primary_key=True),
    Column("tax_id", String(9)),
    Column("name", Text, nullable=False),
    Column("country_code", String(2)),
)

item_contractor = Table(
    "item_contractor",
    metadata,
    Column("item_id", BigInteger, ForeignKey("procurement_item.id"), primary_key=True),
    Column("contractor_id", BigInteger, ForeignKey("contractor.id"), primary_key=True),
    Column("role", String(16), primary_key=True),
    Column("amount_eur", Numeric(18, 2)),
)
